// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestStop.Api.Data;

#nullable disable

namespace RestStop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401164209_AddUserIsActive")]
    partial class AddUserIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestStop.Api.Models.FlexPassParker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPushError")
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyKastlParkerReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PassExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SentToMyKastl")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SentToMyKastlAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PassNumber")
                        .IsUnique();

                    b.HasIndex("SentToMyKastl");

                    b.HasIndex("UserId");

                    b.ToTable("FlexPassParkers");
                });

            modelBuilder.Entity("RestStop.Api.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<bool>("ClaimedByOwner")
                        .HasColumnType("boolean");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GasPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("HoursOpen")
                        .HasColumnType("text");

                    b.Property<bool>("Is24Hr")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "GIST");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RestStop.Api.Models.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Recipient");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("RestStop.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RestStop.Api.Models.Restroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgCleanliness")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgOverall")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSmell")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSupplies")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasBabyStation")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasShower")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAccessible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("StallCount")
                        .HasColumnType("integer");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Type")
                        .IsUnique();

                    b.ToTable("Restrooms");
                });

            modelBuilder.Entity("RestStop.Api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cleanliness")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceFromLocation")
                        .HasColumnType("double precision");

                    b.Property<int>("FlaggedCount")
                        .HasColumnType("integer");

                    b.Property<int>("HelpfulVotes")
                        .HasColumnType("integer");

                    b.Property<double>("LatAtSubmit")
                        .HasColumnType("double precision");

                    b.Property<double>("LngAtSubmit")
                        .HasColumnType("double precision");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<bool>("PhotoAttached")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoS3Key")
                        .HasColumnType("text");

                    b.Property<Guid>("RestroomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Smell")
                        .HasColumnType("integer");

                    b.Property<int>("Supplies")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightApplied")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RestroomId");

                    b.HasIndex("UserId", "RestroomId", "CreatedAt");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RestStop.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppleId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TrustWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppleId")
                        .IsUnique()
                        .HasFilter("\"AppleId\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("\"Phone\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestStop.Api.Models.FlexPassParker", b =>
                {
                    b.HasOne("RestStop.Api.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestStop.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestStop.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("RestStop.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestStop.Api.Models.Restroom", b =>
                {
                    b.HasOne("RestStop.Api.Models.Location", "Location")
                        .WithMany("Restrooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RestStop.Api.Models.Review", b =>
                {
                    b.HasOne("RestStop.Api.Models.Restroom", "Restroom")
                        .WithMany("Reviews")
                        .HasForeignKey("RestroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestStop.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestStop.Api.Models.Location", b =>
                {
                    b.Navigation("Restrooms");
                });

            modelBuilder.Entity("RestStop.Api.Models.Restroom", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RestStop.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
